name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Get tag name
      id: tag
      run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create release directory
      run: mkdir -p release
      
    - name: Copy JAR to release directory
      run: |
        cp target/jms-gui-sender-*.jar release/jms-gui-sender.jar
        cp run.sh release/
        chmod +x release/run.sh
        
    - name: Create README for release
      run: |
        cat > release/README.txt << 'EOF'
        JMS GUI Sender - Release ${{ steps.tag.outputs.tag_name }}
        
        This package contains:
        - jms-gui-sender.jar: The main executable JAR file
        - run.sh: Shell script to run the application
        
        Requirements:
        - Java 21 or higher
        - JavaFX runtime (included in the JAR)
        
        To run:
        1. Make sure Java 21+ is installed
        2. Run: java -jar jms-gui-sender.jar
        3. Or use the provided script: ./run.sh
        
        For more information, see: https://github.com/${{ github.repository }}
        EOF
        
    - name: Create ZIP archive
      run: |
        cd release
        zip -r ../jms-gui-sender-${{ steps.tag.outputs.tag_name }}.zip .
        cd ..
        
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag_name }}
        release_name: JMS GUI Sender ${{ steps.tag.outputs.tag_name }}
        body: |
          Release ${{ steps.tag.outputs.tag_name }} of JMS GUI Sender
          
          ## Download
          Download the ZIP file below and extract it to get the executable JAR and run script.
          
          ## Requirements
          - Java 21 or higher
          
          ## Running the Application
          ```bash
          java -jar jms-gui-sender.jar
          ```
          
          Or use the provided run script:
          ```bash
          ./run.sh
          ```
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./jms-gui-sender-${{ steps.tag.outputs.tag_name }}.zip
        asset_name: jms-gui-sender-${{ steps.tag.outputs.tag_name }}.zip
        asset_content_type: application/zip